SELECT
    sample_name                                   AS sample_name,
    runtime_hours                                 AS runtime_hours,
    absolute_timestamp                            AS absolute_timestamp,
    sensor_type                                   AS sensor_type,
    number_of_cells                               AS number_of_cells,
    IVnumber                                      AS IVnumber,
    ccm_type                                      AS ccm_type,
    tAndeIn                                       AS tAndeIn,
    pAndeOut                                      AS pAndeOut,
    pCtdeOut                                      AS pCtdeOut,
    vfAndeIn                                      AS vfAndeIn,
    jStck                                         AS jStck,
    uCellAvg                                      AS uCellAvg,
    uStck                                         AS uStck,
    uCells_array                                  AS uCells_array,
    soh_lin_stack                                 AS soh_lin_stack,
    soh_kin_stack                                 AS soh_kin_stack,
    soh_lin_cells                                 AS soh_lin_cells,
    soh_kin_cells                                 AS soh_kin_cells,
    model_min_obj_stack                           AS model_min_obj_stack,
    model_min_obj_cells                           AS model_min_obj_cells,
    model_uPred_stack                             AS model_uCell_pred_stack,
    is_rising                                     AS is_rising,
    `model_uCellAvg_ref_pCtdeOut-34tAndeOut-70_stack` AS `model_uCellAvg_ref_pCtdeOut-34tAndeOut-70_stack`,
    `model_uCellAvg_ref_pCtdeOut-40tAndeAvg-70_stack` AS `model_uCellAvg_ref_pCtdeOut-40tAndeAvg-70_stack`,
    `model_uCellAvg_pc_0-098_stack`,
    `model_uCellAvg_pc_0-196_stack`,
    `model_uCellAvg_pc_0-294_stack`,
    `model_uCellAvg_pc_0-588_stack`,
    `model_uCellAvg_pc_0-809_stack`,
    `model_uCellAvg_pc_1-005_stack`,
    `model_uCellAvg_pc_1-201_stack`,
    `model_uCellAvg_pc_1-397_stack`,
    `model_uCellAvg_pc_1-593_stack`,
    `model_uCellAvg_pc_1-789_stack`,
    `model_uCellAvg_pc_1-985_stack`,
    `model_uCellAvg_pc_2-206_stack`,
    `model_uCellAvg_pc_2-402_stack`,
    `model_uCellAvg_pc_2-7_stack`,
    `model_uCellAvg_pc_3-0_stack`,
    `model_uCellAvg_BoL-kin_ref_jStck-0-098pAndeOut-2-5pCtdeOut-40tAndeIn-70vfAndeIn-5-2ECSA-1_stack`,
    `model_uCellAvg_BoL-kin_ref_jStck-0-196pAndeOut-2-5pCtdeOut-40tAndeIn-70vfAndeIn-5-2ECSA-1_stack`,
    `model_uCellAvg_BoL-kin_ref_jStck-0-294pAndeOut-2-5pCtdeOut-40tAndeIn-70vfAndeIn-5-2ECSA-1_stack`,
    `model_uCellAvg_BoL-kin_ref_jStck-0-588pAndeOut-2-5pCtdeOut-40tAndeIn-70vfAndeIn-5-2ECSA-1_stack`,
    `model_uCellAvg_BoL-kin_ref_jStck-0-809pAndeOut-2-5pCtdeOut-40tAndeIn-70vfAndeIn-5-2ECSA-1_stack`,
    `model_uCellAvg_BoL-kin_ref_jStck-1-005pAndeOut-2-5pCtdeOut-40tAndeIn-70vfAndeIn-5-2ECSA-1_stack`,
    `model_uCellAvg_BoL-kin_ref_jStck-1-201pAndeOut-2-5pCtdeOut-40tAndeIn-70vfAndeIn-5-2ECSA-1_stack`,
    `model_uCellAvg_BoL-kin_ref_jStck-1-397pAndeOut-2-5pCtdeOut-40tAndeIn-70vfAndeIn-5-2ECSA-1_stack`,
    `model_uCellAvg_BoL-kin_ref_jStck-1-593pAndeOut-2-5pCtdeOut-40tAndeIn-70vfAndeIn-5-2ECSA-1_stack`,
    `model_uCellAvg_BoL-kin_ref_jStck-1-789pAndeOut-2-5pCtdeOut-40tAndeIn-70vfAndeIn-5-2ECSA-1_stack`,
    `model_uCellAvg_BoL-kin_ref_jStck-1-985pAndeOut-2-5pCtdeOut-40tAndeIn-70vfAndeIn-5-2ECSA-1_stack`,
    `model_uCellAvg_BoL-kin_ref_jStck-2-206pAndeOut-2-5pCtdeOut-40tAndeIn-70vfAndeIn-5-2ECSA-1_stack`,
    `model_uCellAvg_BoL-kin_ref_jStck-2-402pAndeOut-2-5pCtdeOut-40tAndeIn-70vfAndeIn-5-2ECSA-1_stack`,
    `model_uCellAvg_BoL-kin_ref_jStck-2-7pAndeOut-2-5pCtdeOut-40tAndeIn-70vfAndeIn-5-2ECSA-1_stack`,
    `model_uCellAvg_BoL-kin_ref_jStck-3-0pAndeOut-2-5pCtdeOut-40tAndeIn-70vfAndeIn-5-2ECSA-1_stack`,
    `model_uCellAvg_BoL-lin_ref_jStck-0-098pAndeOut-2-5pCtdeOut-40tAndeIn-70vfAndeIn-5-2delta_Rohm-0_stack`,
    `model_uCellAvg_BoL-lin_ref_jStck-0-196pAndeOut-2-5pCtdeOut-40tAndeIn-70vfAndeIn-5-2delta_Rohm-0_stack`,
    `model_uCellAvg_BoL-lin_ref_jStck-0-294pAndeOut-2-5pCtdeOut-40tAndeIn-70vfAndeIn-5-2delta_Rohm-0_stack`,
    `model_uCellAvg_BoL-lin_ref_jStck-0-588pAndeOut-2-5pCtdeOut-40tAndeIn-70vfAndeIn-5-2delta_Rohm-0_stack`,
    `model_uCellAvg_BoL-lin_ref_jStck-0-809pAndeOut-2-5pCtdeOut-40tAndeIn-70vfAndeIn-5-2delta_Rohm-0_stack`,
    `model_uCellAvg_BoL-lin_ref_jStck-1-005pAndeOut-2-5pCtdeOut-40tAndeIn-70vfAndeIn-5-2delta_Rohm-0_stack`,
    `model_uCellAvg_BoL-lin_ref_jStck-1-201pAndeOut-2-5pCtdeOut-40tAndeIn-70vfAndeIn-5-2delta_Rohm-0_stack`,
    `model_uCellAvg_BoL-lin_ref_jStck-1-397pAndeOut-2-5pCtdeOut-40tAndeIn-70vfAndeIn-5-2delta_Rohm-0_stack`,
    `model_uCellAvg_BoL-lin_ref_jStck-1-593pAndeOut-2-5pCtdeOut-40tAndeIn-70vfAndeIn-5-2delta_Rohm-0_stack`,
    `model_uCellAvg_BoL-lin_ref_jStck-1-789pAndeOut-2-5pCtdeOut-40tAndeIn-70vfAndeIn-5-2delta_Rohm-0_stack`,
    `model_uCellAvg_BoL-lin_ref_jStck-1-985pAndeOut-2-5pCtdeOut-40tAndeIn-70vfAndeIn-5-2delta_Rohm-0_stack`,
    `model_uCellAvg_BoL-lin_ref_jStck-2-206pAndeOut-2-5pCtdeOut-40tAndeIn-70vfAndeIn-5-2delta_Rohm-0_stack`,
    `model_uCellAvg_BoL-lin_ref_jStck-2-402pAndeOut-2-5pCtdeOut-40tAndeIn-70vfAndeIn-5-2delta_Rohm-0_stack`,
    `model_uCellAvg_BoL-lin_ref_jStck-2-7pAndeOut-2-5pCtdeOut-40tAndeIn-70vfAndeIn-5-2delta_Rohm-0_stack`,
    `model_uCellAvg_BoL-lin_ref_jStck-3-0pAndeOut-2-5pCtdeOut-40tAndeIn-70vfAndeIn-5-2delta_Rohm-0_stack`,
    `model_uCellAvg_BoL_ref_jStck-3-0pAndeOut-2-5pCtdeOut-40tAndeIn-70vfAndeIn-5-2ECSA-1delta_Rohm-0_stack`,
    `model_uCellAvg_pc_3-0_cells`,
    `model_uCellAvg_BoL-kin_ref_jStck-3-0pAndeOut-2-5pCtdeOut-40tAndeIn-70vfAndeIn-5-2ECSA-1_cells`,
    `model_uCellAvg_BoL-lin_ref_jStck-3-0pAndeOut-2-5pCtdeOut-40tAndeIn-70vfAndeIn-5-2delta_Rohm-0_cells`


FROM ps_xplatform_dev.pemely_dev.gold_virtual_sensor_soh_cr_sherlock

WHERE sample_name = '{sample_name}'

ORDER BY
    sample_name,
    sensor_type,
    runtime_hours;

